ARG ECR_URL
ARG REPO_NAME
ARG STAGE
# This is temporary, will need to updated the values for the ECR_URL and REPO_NAME in Github secrets
FROM public.ecr.aws/x0k5y3h8/etherealengine-qat-root:latest_${STAGE} as builder

COPY . .

COPY packages/server/package.json ./packages/server/
RUN npm install --loglevel notice --legacy-peer-deps --production

CMD ["scripts/strip-engine.sh"]

# copy then compile the code

ENV APP_ENV=production

FROM node:18-buster-slim as runner
WORKDIR /app

# This commands runs the setup_helm.sh script to install helm and relevent installations
COPY ../../scripts/setup_helm.sh .
RUN chmod +x setup_helm.sh && ./setup_helm.sh


COPY --from=builder /app ./

CMD ["scripts/run-builder.sh"]
